### ISSUE TITLE
cb is not a function

### ISSUE THREAD

**Issue by eeeeeeeason** [yun2win/yun2win-sdk-server#1]
TypeError: cb is not a function
    at /Users/yucheng/Desktop/webRTC/server/yun2win-sdk-server/app/core/userConversations.js:68:13
    at /Users/yucheng/Desktop/webRTC/server/yun2win-sdk-server/node_modules/thenjs/then.js:361:15
    at continuationExec (/Users/yucheng/Desktop/webRTC/server/yun2win-sdk-server/node_modules/thenjs/then.js:295:33)
    at carry (/Users/yucheng/Desktop/webRTC/server/yun2win-sdk-server/node_modules/thenjs/then.js:54:10)
    at Thenjs.continuation (/Users/yucheng/Desktop/webRTC/server/yun2win-sdk-server/node_modules/thenjs/then.js:281:5)
    at cont (/Users/yucheng/Desktop/webRTC/server/yun2win-sdk-server/node_modules/thenjs/then.js:325:27)
    at parallel (/Users/yucheng/Desktop/webRTC/server/yun2win-sdk-server/node_modules/thenjs/then.js:372:30)
    at self._parallel (/Users/yucheng/Desktop/webRTC/server/yun2win-sdk-server/node_modules/thenjs/then.js:210:9)
    at continuationExec (/Users/yucheng/Desktop/webRTC/server/yun2win-sdk-server/node_modules/thenjs/then.js:295:33)
    at carry (/Users/yucheng/Desktop/webRTC/server/yun2win-sdk-server/node_modules/thenjs/then.js:54:10)
    at Thenjs.continuation (/Users/yucheng/Desktop/webRTC/server/yun2win-sdk-server/node_modules/thenjs/then.js:281:5)
    at cont (/Users/yucheng/Desktop/webRTC/server/yun2win-sdk-server/node_modules/thenjs/then.js:325:27)
    at /Users/yucheng/Desktop/webRTC/server/yun2win-sdk-server/app/core/userConversations.js:52:13
    at /Users/yucheng/Desktop/webRTC/server/yun2win-sdk-server/node_modules/thenjs/then.js:361:15
    at continuationExec (/Users/yucheng/Desktop/webRTC/server/yun2win-sdk-server/node_modules/thenjs/then.js:295:33)
    at carry (/Users/yucheng/Desktop/webRTC/server/yun2win-sdk-server/node_modules/thenjs/then.js:54:10)

**Comment by eeeeeeeason** [comment]
不知道哪传的回调函数。跑不起来
